# Compile and link the application
all: main

# Run the application
run: main
	./main

# Link main.o and TTT.o to create the executable "main"
main: main.o TTT.o
	gcc -g -o main main.o TTT.o

# Compile main.c to main.o
main.o: main.c
	gcc -g -c main.c -o main.o

# Compile TTT.c to TTT.o
TTT.o: TTT.c
	gcc -g -c TTT.c -o TTT.o

# Remove built files
clean:
	rm -rf main main.o TTT.o *~
